const RewardsActionsType = {
    ADD_CATEGORY: 'ADD_CATEGORY',
    REMOVE_CATEGORY: 'REMOVE_CATEGORY',
    STORE_CATEGORY: 'STORE_CATEGORY',
    UPDATE_REWARD_POSITION: 'UPDATE_REWARD_POSITION'
};

export default RewardsActionsType;
