const RewardsActionsType = {
    ADD_CATEGORY: 'ADD_CATEGORY',
    REMOVE_CATEGORY: 'REMOVE_CATEGORY',
    STORE_CATEGORY: 'STORE_CATEGORY',
    UPDATE_CATEGORY_POSITION: 'UPDATE_CATEGORY_POSITION' 
};

export default RewardsActionsType;
